### PR TITLE
attach animation when other user moving sticky

### PR DESCRIPTION
**Pull request by higumachan**
Now, when other user moving sticky, suddenly move.
This feature, when other user moving sticky, animated move!

### CODE REVIEW

**Comment by higumachan** [comment]
英語ヘタでごめんなさい。
他のユーザがstickyを動かした時にとつぜん動くのではなく、アニメーションを入れました

**Comment by lunardog** [comment]
I like your idea. 

Since the style you added is constant, how about putting it in the CSS? 

This should have the same effect:

```
.sticky.dragging {
  transition-duration: 4s;
  transition-property: left top transform;
}
```

**Comment by lunardog** [comment]
Oops! Opposite:

```
.sticky {
  transition-duration: 1s;
  transition-property: left top transform;
}

.sticky.dragging {
  transition-property: none;
}
```

**Comment by higumachan** [comment]
It's nice idea!
I'll do it!

**Pull request merged**
